apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gep-poc-tha-container
spec:
  replicas: 1
  template:
    metadata:
      labels:
	app: gep-poc-tha-app
    spec:
      containers:
        - name: nginx-container
          imagePullPolicy: Always
          image: mithunvikram/gep-poc-tha-grapejs:2.0
          ports:
            - name: http-port
              containerPort: 80

